### ISSUE TITLE
Distillery/Oven/Loom/Apiary GUI misbehaving

### ISSUE THREAD

**Issue by olol5620** [zabi94/Covens-reborn#11]
#### Mod version:  
1.12.2-0.0.20 
#### Minecraft version:  
1.12.2
#### Operative System and OS version:  
ubuntu 18.04.1 LTS
#### Modlist (use pastebin or similar):  
https://pastebin.com/m1maDrYP
#### Steps to reproduce:  
open GUI of Distillery and try click some items into the Fields:
Items get immediately unclicked, no shift clicking. Hopping Items work, but no recipe. 
Items that do work are items that don't belong in there

**Comment by olol5620** [comment]
only on multiplayer server

**Comment by zabi94** [comment]
This also apply to the loom inventory, apparently

**Comment by olol5620** [comment]
and the apiary.

**Comment by olol5620** [comment]
it also seems to desync the player inventory from server
