### ISSUE TITLE
Goblet/Crystall Bell/Boline/Arthame/Candle on Altar considered as full blocks

### ISSUE THREAD

**Issue by olol5620** [zabi94/Covens-reborn#14]
#### Feature requested:
Placed items, Goblet, Crystall Bell and Candles need their block face shape set to undefined, otherwise you can attach vines and torches on their side

**Comment by zabi94** [comment]
This is not doable without implementing Forge Multipart, which would be a mess

**Comment by olol5620** [comment]
but for example skulls work like this

**Comment by zabi94** [comment]
Pretty sure they don't... Unless you install forge multipart

**Comment by olol5620** [comment]
I testet it in a fresh vanilla 1.12.2 world and I'm not be able to place a torch against a skull, leaves or flowers for that matter

**Comment by zabi94** [comment]
Just like all the items from covens. That's normal
