### ISSUE TITLE
Elder wood texture don't match there planks counterpart

### ISSUE THREAD

**Issue by olol5620** [zabi94/Covens-reborn#15]
#### Feature requested:
Either The elder wood texture or the planks texture should be brightened /darkened.
https://imgur.com/a/jbBCXYv
manufacturing the planks would require a bleaching step

**Comment by zabi94** [comment]
Would changing the name to Elder Bark planks fix that for you? They're supposed to have the exterior color

**Comment by olol5620** [comment]
Honestly I don't care, because for building I don't use the log top very often and the planks/log bark looks isolated good.

**Comment by olol5620** [comment]
I think renaming it won't be useful, especially when you want to search for it in jei/ME-System/Chest...
