### ISSUE TITLE
Optifine messes with non full blocks with offset

### ISSUE THREAD

**Issue by olol5620** [zabi94/Covens-reborn#16]
#### Mod version:  
1.12.2-0.0.20   
#### Minecraft version:  
1.12.2
#### Operative System and OS version:  
ubuntu 18.04.1 LTS
#### Modlist (use pastebin or similar):  
https://pastebin.com/m1maDrYP
#### Steps to reproduce:  
walk slowly (i.e sneaking) against goblet/candles
player gets reset after colliding with the hitbox. 
Can be forced if there is a block two blocks above goblet/candle 
https://imgur.com/a/yaXXWa3

**Comment by olol5620** [comment]
apparently only when coming from east /south side (facing west /north)

**Comment by olol5620** [comment]
on multiplayer server only

**Comment by zabi94** [comment]
Is this still happening? If yes it's probably some other mod interfering, because I can't reproduce this in the latest build with a minimal mod list

**Comment by olol5620** [comment]
indeed with a minimal setup both the hitbox alignment and getting stuck problem are fixed. must be a mod interference of the list provided (didn't add nor updated other mods)

**Comment by zabi94** [comment]
Check, adding one by one, FoamFix, VanillaFix, Optifine and the AI Improvement mods, if you got the chance, those are my main suspects. It would save me a lot of time if you can do that.

**Comment by olol5620** [comment]
aaaand... it is Optifine

**Comment by zabi94** [comment]
Well, f**k. The only one I can't fix properly. I'll add a workaround I guess 😒

**Comment by olol5620** [comment]
disable all candle, gobelts and so on, when Optifine is detected :P

**Comment by zabi94** [comment]
I'll disable the offset and make them centered if it's installed
