### ISSUE TITLE
Werewolves don't render at all

### ISSUE THREAD

**Issue by Snakefangox** [zabi94/Covens-reborn#19]
#### Mod version:  
0.0.23
#### Minecraft version:  
1.12.2
#### Operative System and OS version:  
Windows 10 1803
#### Modlist (use pastebin or similar):  
- Baubles
- Covens Reborn
- Minerva Library
- OpenEye
- Patchouli

Werewolves don't appear to render in the latest release.
![image](https://user-images.githubusercontent.com/14956300/52081851-2559ac00-2600-11e9-9557-8f2defbca593.png)

**Comment by zabi94** [comment]
The werewolf model has been temporarily disabled as the code handling the animations was not in a maintainable state. It will come back when it's in a more stable state
