### ISSUE TITLE
Shift Clicking won't always work

### ISSUE THREAD

**Issue by olol5620** [zabi94/Covens-reborn#23]
#### Mod version:  
1.12.2-0.0.24
#### Minecraft version:  
1.12.2
#### Operative System and OS version:  
ubuntu 18.04.1 LTS
#### Modlist (use pastebin or similar):  
https://pastebin.com/nYHgYjC2
#### Steps to reproduce:  
Oven: Shift in works, shift out (upper(ash) and lower(full jar) slot) don't work
Apiary: Neither in nor out works
Loom: Neither in nor out works
Distillery: Neither in nor out works

**Comment by zabi94** [comment]
Yeah, it's one of the last things I implement usually, I hate adding that functionality, and I want to have something to do that for me automatically, in the future
