### ISSUE TITLE
Possible shared errors

### ISSUE THREAD

**Issue by Sunconure11** [zabi94/Covens-reborn#24]
- [x] https://github.com/Um-Mitternacht/Bewitchment/issues/224
- [x] https://github.com/Um-Mitternacht/Bewitchment/issues/223
- [x] https://github.com/Um-Mitternacht/Bewitchment/issues/222
- [ ] https://github.com/Um-Mitternacht/Bewitchment/issues/221
- [x] https://github.com/Um-Mitternacht/Bewitchment/issues/212
- [x] https://github.com/Um-Mitternacht/Bewitchment/issues/210

**Comment by zabi94** [comment]
212 is already fixed for me, I'm just waiting to collect more changes before pushing. Most of the others I already know where to fix

**Comment by zabi94** [comment]
224 is also not affecting covens

**Comment by zabi94** [comment]
222 also is not affecting covens

**Comment by Sunconure11** [comment]
I did increase the amount of allowed items on an altar, perhaps that could have something to do with it?

https://github.com/Um-Mitternacht/Bewitchment/blob/bf31b5a2a84b7bca82ca3df649ad8187848e0285/src/main/java/com/bewitchment/common/tile/tiles/TileEntityWitchAltar.java

https://github.com/Um-Mitternacht/Bewitchment/blob/4402ff938bc2122245d54e02f077ac35bd9fec76/src/main/java/com/bewitchment/common/block/tiles/BlockWitchAltar.java

**Comment by zabi94** [comment]
Which one are you referring to?

**Comment by Sunconure11** [comment]
224

**Comment by zabi94** [comment]
No, it's linked to the fact that in that class you should check what block is the one you're rendering. The clientside gets the tile entity before the block, so for a few milliseconds you're trying to get the direction of an AIR block, which makes no sense

**Comment by Sunconure11** [comment]
... fuck

**Comment by zabi94** [comment]
Just add a check at the beginning of the renderer, making sure it's your block

**Comment by Sunconure11** [comment]
Example? Because I feel kind of dumb ATM, that this was missed. And I'm trying to fix another mod that is used on the BW server

**Comment by Sunconure11** [comment]
https://github.com/Um-Mitternacht/Bewitchment/issues/207

This on your end too?

**Comment by Sunconure11** [comment]
https://github.com/Um-Mitternacht/Bewitchment/issues/231

**Comment by zabi94** [comment]
I'll close this, and open a new issue for the one error I haven't been able to fix. Don't worry about reporting other ones, I'm still in the BW github org, I get the notifications automatically
