### ISSUE TITLE
Guardian-related crash, I assume

### ISSUE THREAD

**Issue by dmtRoyal** [zabi94/Covens-reborn#52]
#### What were you doing when you crashed:
Trying to open the creative tabs so I could test things

#### Pastebin of latest.log file:
https://pastebin.com/f7p7BSDR

#### Pastebin of the FULL crashlog (should contain modlist + versions):
https://pastebin.com/GshHyYhT

#### Your sided configuration:

[X] Single player  
[ ] Single player, with other players playing in your world through "open to lan"  
[ ] Multiplayer, on a dedicated server  
[ ] Multiplayer, on a lan-opened single player world  

#### Other useful info:
I have this bag of saltines on my desk and I don't know how old they are but I fully plan on eating them (this is a joke, the crash log is not)

**Comment by zabi94** [comment]
Yeah, this is already fixed in my dev env, waiting for the public indev build
