### ISSUE TITLE
Ravens assault players for food

### ISSUE THREAD

**Issue by dmtRoyal** [zabi94/Covens-reborn#53]
#### Have you tried searching if this was already suggested?
YES 

#### If yes, what did you search for? and where?
"Raven", both here and on Discord

#### Describe your suggestion:
Rather than have ravens sitting on the ground waiting to have gold nuggets stuffed down their beaks, perhaps have them fly a certain height above the ground and, if a player is holding (moderate chance) or eating (higher chance) food like steak, porkchops, mutton, etc., a raven might swoop down and take the food item away.  I've actually seen this behavior personally; ravens are scavengers, but they're also pretty mischievous, so they sometimes like to mess with people.

**Comment by zabi94** [comment]
Flying creatures are a pain to mess with, I'd rather not touch them if possible
