### ISSUE TITLE
Game crashes when mob attacks something

### ISSUE THREAD

**Issue by Hollexian** [zabi94/Covens-reborn#54]
#### Mod version:  
0.0.27
#### Minecraft version:  
1.12.2
#### Operative System and OS version:  
Windows 10, version 1803
#### Modlist (use pastebin or similar):  
https://pastebin.com/NVAQzBsC
#### Log file (latest.log, uploaded to pastebin):  
https://pastebin.com/hHZZNFRq
#### Steps to reproduce:  
1. Spawn a Mob
(optional - spawn an animal, if not, use yourself)
2. Get mob to attack you/animal
3. Crash
---

**Comment by zabi94** [comment]
Can I get your discord tag? I need to update the proper testers, I was about to refresh them
