### ISSUE TITLE
Crash creeper explosion?

### ISSUE THREAD

**Issue by PixelEyeStudios** [zabi94/Covens-reborn#58]
#### Crash log (uploaded to pastebin):  
https://pastebin.com/gk9BUqbk
#### Steps to reproduce:  
Not entirely sure what I did, I had scrolls in my inventory, put myself into survival and ran with a scroll in my hand because there were creepers by my altar. I ran past a few but I think one of them exploded (didn't hear or see anything) and then crash.

**Comment by zabi94** [comment]
Same bug as the last report. Everytime someone deals damage to someone else, entity or not, you're going to crash
