### ISSUE TITLE
Mod Conflicting Crash

### ISSUE THREAD

**Issue by MagicMaxcer** [zabi94/Covens-reborn#70]
#### Minecraft version:  
1.12.2
#### Operative System and OS version:  

EmberRoot Zoo 

#### Steps to reproduce:  
EmberRoot Zoo <<< this mod and coven reborn
#### Screenshots, if relevant:  

---
#### Additional information that might be useful:  

---
#### Feature requested:

---

**Comment by zabi94** [comment]
This tells me absolutely nothing. I need a crash log
