### ISSUE TITLE
hitbox of some blocks not aligned with rendered blocks

### ISSUE THREAD

**Issue by olol5620** [zabi94/Covens-reborn#8]
#### Mod version:  
0.0.1.6
#### Minecraft version:  
1.12.2
#### Operative System and OS version:  
ubuntu 18.04.1 LTS
#### Modlist (use pastebin or similar):  
https://pastebin.com/ER0xhmaC
#### Steps to reproduce:  
The both candles and both goblets hitbox is not aligned with the actual rendered blocks
#### Screenshots, if relevant:  
https://imgur.com/a/TBxHSmz

**Comment by zabi94** [comment]
Pretty sure this and #16 are the same problem
